stages:
  - build-maven
  - build-docker

build-maven:
  stage: build-maven
  image: maven:3.8-openjdk-16
  variables:
    MAVEN_OPTS: '-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository'
  script:
    - mvn clean compile verify package
  cache:
    key: 'maven-local-repository-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - '.m2/repository'
  artifacts:
    paths:
      - target/ones-backend.jar

build-docker:
  stage: build-docker
  dependencies:
    - build-maven
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination docker.io/fourtyseveneleven/ones-backend:latest

