image: maven:3.8-openjdk-16

stages:
  - ci

ci:
  stage: ci
  variables:
    MAVEN_OPTS: '-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository'
  script:
    - mvn clean compile verify
  cache:
    key: 'maven-local-repository-$CI_JOB_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - '.m2/repository'
