package de.fourtyseveneleven.ones.event.model;

public enum ContestType {

    INTRODUCTION_RIDE, INTRODUCTION_DRIVE,
    SHORT_DISTANCE_RIDE, SHORT_DISTANCE_DRIVE,
    MEDIUM_DISTANCE_RIDE, MEDIUM_DISTANCE_DRIVE,
    LONG_DISTANCE_RIDE, LONG_DISTANCE_DRIVE,
    MULTIPLE_DAY_RIDE, MULTIPLE_DAY_DRIVE
}
